package net.ledok.arenas_ld.networking;

import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry;
import net.ledok.arenas_ld.dungeon.packet.DbsClearRoomsPayload;
import net.ledok.arenas_ld.dungeon.packet.DbsMoveRoomPayload;
import net.ledok.arenas_ld.dungeon.packet.DbsRemoveRoomPayload;
import net.ledok.arenas_ld.dungeon.packet.DungeonBossSpawnerSnapshotPayload;
import net.ledok.arenas_ld.dungeon.packet.DungeonControllerAdminSnapshotPayload;
import net.ledok.arenas_ld.dungeon.packet.DungeonControllerSnapshotPayload;
import net.ledok.arenas_ld.dungeon.packet.MobSpawnerSnapshotPayload;
import net.ledok.arenas_ld.dungeon.packet.AddDungeonInstancePayload;
import net.ledok.arenas_ld.dungeon.packet.AcceptInvitePayload;
import net.ledok.arenas_ld.dungeon.packet.AcceptJoinRequestPayload;
import net.ledok.arenas_ld.dungeon.packet.CreateLobbyPayload;
import net.ledok.arenas_ld.dungeon.packet.DeclineInvitePayload;
import net.ledok.arenas_ld.dungeon.packet.DeclineJoinRequestPayload;
import net.ledok.arenas_ld.dungeon.packet.InvitePlayerPayload;
import net.ledok.arenas_ld.dungeon.packet.JoinLobbyPayload;
import net.ledok.arenas_ld.dungeon.packet.RequestJoinPayload;
import net.ledok.arenas_ld.dungeon.packet.KickFromLobbyPayload;
import net.ledok.arenas_ld.dungeon.packet.LeaveLobbyPayload;
import net.ledok.arenas_ld.dungeon.packet.MoveDungeonInstancePayload;
import net.ledok.arenas_ld.dungeon.packet.RemoveDungeonInstancePayload;
import net.ledok.arenas_ld.dungeon.packet.RoomClearDoorPayload;
import net.ledok.arenas_ld.dungeon.packet.RoomClearSpawnersPayload;
import net.ledok.arenas_ld.dungeon.packet.RoomControllerSnapshotPayload;
import net.ledok.arenas_ld.dungeon.packet.RoomRemoveSpawnerPayload;
import net.ledok.arenas_ld.dungeon.packet.RoomResetPayload;
import net.ledok.arenas_ld.dungeon.packet.SetLobbyTierPayload;
import net.ledok.arenas_ld.dungeon.packet.SetLobbyHardcorePayload;
import net.ledok.arenas_ld.dungeon.packet.SetLobbyVisibilityPayload;
import net.ledok.arenas_ld.dungeon.packet.SetCloseTimerSecondsPayload;
import net.ledok.arenas_ld.dungeon.packet.SetCooldownTicksPayload;
import net.ledok.arenas_ld.dungeon.packet.SetInviteExpiryTicksPayload;
import net.ledok.arenas_ld.dungeon.packet.SetLootViaInboxPayload;
import net.ledok.arenas_ld.dungeon.packet.SetMaxPartySizePayload;
import net.ledok.arenas_ld.dungeon.packet.SetRespawnTimeTicksPayload;
import net.ledok.arenas_ld.dungeon.packet.SetDeathTimePenaltyPayload;
import net.ledok.arenas_ld.dungeon.packet.SetTierConfigPayload;
import net.ledok.arenas_ld.dungeon.packet.StartRunPayload;
import net.ledok.arenas_ld.dungeon.packet.ToggleReadyPayload;
import net.ledok.arenas_ld.dungeon.packet.UpdateDbsEntityDefPayload;
import net.ledok.arenas_ld.dungeon.packet.UpdateMobSpawnerEntityDefPayload;
import net.ledok.arenas_ld.raid.packet.RaidAcceptInvitePayload;
import net.ledok.arenas_ld.raid.packet.RaidAcceptJoinRequestPayload;
import net.ledok.arenas_ld.raid.packet.RaidControllerAdminSnapshotPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetMaxPartySizePayload;
import net.ledok.arenas_ld.raid.packet.RaidSetRespawnTimeTicksPayload;
import net.ledok.arenas_ld.raid.packet.RaidMoveInstancePayload;
import net.ledok.arenas_ld.raid.packet.RaidRemoveInstancePayload;
import net.ledok.arenas_ld.raid.packet.RaidSetCloseTimerSecondsPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetCooldownTicksPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetInviteExpiryTicksPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetTierConfigPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetDeathTimePenaltyPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetLootViaInboxPayload;
import net.ledok.arenas_ld.raid.packet.RaidControllerSnapshotPayload;
import net.ledok.arenas_ld.raid.packet.RaidCreateLobbyPayload;
import net.ledok.arenas_ld.raid.packet.RaidDeclineInvitePayload;
import net.ledok.arenas_ld.raid.packet.RaidDeclineJoinRequestPayload;
import net.ledok.arenas_ld.raid.packet.RaidInvitePlayerPayload;
import net.ledok.arenas_ld.raid.packet.RaidJoinLobbyPayload;
import net.ledok.arenas_ld.raid.packet.RaidKickFromLobbyPayload;
import net.ledok.arenas_ld.raid.packet.RaidLeaveLobbyPayload;
import net.ledok.arenas_ld.raid.packet.RaidRequestJoinPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetLobbyHardcorePayload;
import net.ledok.arenas_ld.raid.packet.RaidSetLobbyTierPayload;
import net.ledok.arenas_ld.raid.packet.RaidSetLobbyVisibilityPayload;
import net.ledok.arenas_ld.raid.packet.RaidStartRunPayload;
import net.ledok.arenas_ld.raid.packet.RaidToggleReadyPayload;

import static net.ledok.arenas_ld.networking.ModPackets.*;

final class ModPacketTypeRegistry {
    private ModPacketTypeRegistry() {
    }

    static void registerC2STypes() {
        PayloadTypeRegistry.playC2S().register(UpdateBossSpawnerPayload.TYPE, UpdateBossSpawnerPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateMobArenaSpawnerPayload.TYPE, UpdateMobArenaSpawnerPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateMobArenaMobsPayload.TYPE, UpdateMobArenaMobsPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateMobArenaRewardsPayload.TYPE, UpdateMobArenaRewardsPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateAttributesPayload.TYPE, UpdateAttributesPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateEquipmentPayload.TYPE, UpdateEquipmentPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(CycleLinkerModePayload.TYPE, CycleLinkerModePayload.CODEC);
        PayloadTypeRegistry.playC2S().register(CycleConfiguratorModePayload.TYPE, CycleConfiguratorModePayload.CODEC);
        PayloadTypeRegistry.playC2S().register(MobArenaControllerActionPayload.TYPE, MobArenaControllerActionPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RequestMobArenaControllerInfoPayload.TYPE, RequestMobArenaControllerInfoPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateMobArenaControllerSettingsPayload.TYPE, UpdateMobArenaControllerSettingsPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RoomRemoveSpawnerPayload.TYPE, RoomRemoveSpawnerPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RoomClearSpawnersPayload.TYPE, RoomClearSpawnersPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RoomClearDoorPayload.TYPE, RoomClearDoorPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RoomResetPayload.TYPE, RoomResetPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateMobSpawnerEntityDefPayload.TYPE, UpdateMobSpawnerEntityDefPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(UpdateDbsEntityDefPayload.TYPE, UpdateDbsEntityDefPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DbsRemoveRoomPayload.TYPE, DbsRemoveRoomPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DbsMoveRoomPayload.TYPE, DbsMoveRoomPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DbsClearRoomsPayload.TYPE, DbsClearRoomsPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(CreateLobbyPayload.TYPE, CreateLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(JoinLobbyPayload.TYPE, JoinLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(InvitePlayerPayload.TYPE, InvitePlayerPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(AcceptInvitePayload.TYPE, AcceptInvitePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DeclineInvitePayload.TYPE, DeclineInvitePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RequestJoinPayload.TYPE, RequestJoinPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(AcceptJoinRequestPayload.TYPE, AcceptJoinRequestPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(DeclineJoinRequestPayload.TYPE, DeclineJoinRequestPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(LeaveLobbyPayload.TYPE, LeaveLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(KickFromLobbyPayload.TYPE, KickFromLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetLobbyTierPayload.TYPE, SetLobbyTierPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetLobbyHardcorePayload.TYPE, SetLobbyHardcorePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetLobbyVisibilityPayload.TYPE, SetLobbyVisibilityPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(ToggleReadyPayload.TYPE, ToggleReadyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(StartRunPayload.TYPE, StartRunPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(AddDungeonInstancePayload.TYPE, AddDungeonInstancePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RemoveDungeonInstancePayload.TYPE, RemoveDungeonInstancePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(MoveDungeonInstancePayload.TYPE, MoveDungeonInstancePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetCooldownTicksPayload.TYPE, SetCooldownTicksPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetCloseTimerSecondsPayload.TYPE, SetCloseTimerSecondsPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetMaxPartySizePayload.TYPE, SetMaxPartySizePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetRespawnTimeTicksPayload.TYPE, SetRespawnTimeTicksPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetDeathTimePenaltyPayload.TYPE, SetDeathTimePenaltyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetInviteExpiryTicksPayload.TYPE, SetInviteExpiryTicksPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetLootViaInboxPayload.TYPE, SetLootViaInboxPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(SetTierConfigPayload.TYPE, SetTierConfigPayload.STREAM_CODEC);
        // New raid packets
        PayloadTypeRegistry.playC2S().register(RaidCreateLobbyPayload.TYPE, RaidCreateLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidLeaveLobbyPayload.TYPE, RaidLeaveLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidStartRunPayload.TYPE, RaidStartRunPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidInvitePlayerPayload.TYPE, RaidInvitePlayerPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidAcceptInvitePayload.TYPE, RaidAcceptInvitePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidDeclineInvitePayload.TYPE, RaidDeclineInvitePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidKickFromLobbyPayload.TYPE, RaidKickFromLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetLobbyTierPayload.TYPE, RaidSetLobbyTierPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetLobbyHardcorePayload.TYPE, RaidSetLobbyHardcorePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetLobbyVisibilityPayload.TYPE, RaidSetLobbyVisibilityPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidToggleReadyPayload.TYPE, RaidToggleReadyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidJoinLobbyPayload.TYPE, RaidJoinLobbyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidRequestJoinPayload.TYPE, RaidRequestJoinPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidAcceptJoinRequestPayload.TYPE, RaidAcceptJoinRequestPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidDeclineJoinRequestPayload.TYPE, RaidDeclineJoinRequestPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetRespawnTimeTicksPayload.TYPE, RaidSetRespawnTimeTicksPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetMaxPartySizePayload.TYPE, RaidSetMaxPartySizePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidRemoveInstancePayload.TYPE, RaidRemoveInstancePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidMoveInstancePayload.TYPE, RaidMoveInstancePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetCooldownTicksPayload.TYPE, RaidSetCooldownTicksPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetCloseTimerSecondsPayload.TYPE, RaidSetCloseTimerSecondsPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetInviteExpiryTicksPayload.TYPE, RaidSetInviteExpiryTicksPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetTierConfigPayload.TYPE, RaidSetTierConfigPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetDeathTimePenaltyPayload.TYPE, RaidSetDeathTimePenaltyPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(RaidSetLootViaInboxPayload.TYPE, RaidSetLootViaInboxPayload.STREAM_CODEC);

        // ── Arena (reworked) C2S ────────────────────────────────────────────────
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaLobbyActionPayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaLobbyActionPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaLobbyTargetPayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaLobbyTargetPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaSetVisibilityPayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaSetVisibilityPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaSetHardcorePayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaSetHardcorePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaAdminSetIntPayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaAdminSetIntPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaAdminSetBoolPayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaAdminSetBoolPayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaSetRewardCurvePayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaSetRewardCurvePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaMoveInstancePayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaMoveInstancePayload.STREAM_CODEC);
        PayloadTypeRegistry.playC2S().register(net.ledok.arenas_ld.arena.packet.ArenaRemoveInstancePayload.TYPE, net.ledok.arenas_ld.arena.packet.ArenaRemoveInstancePayload.STREAM_CODEC);
    }

    static void registerS2CTypes() {
        PayloadTypeRegistry.playS2C().register(RaidControllerInfoPayload.TYPE, RaidControllerInfoPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(RaidControllerSnapshotPayload.TYPE, RaidControllerSnapshotPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(MobArenaControllerInfoPayload.TYPE, MobArenaControllerInfoPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(DungeonControllerSnapshotPayload.TYPE, DungeonControllerSnapshotPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(RoomControllerSnapshotPayload.TYPE, RoomControllerSnapshotPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(MobSpawnerSnapshotPayload.TYPE, MobSpawnerSnapshotPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(DungeonBossSpawnerSnapshotPayload.TYPE, DungeonBossSpawnerSnapshotPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(DungeonControllerAdminSnapshotPayload.TYPE, DungeonControllerAdminSnapshotPayload.STREAM_CODEC);
        PayloadTypeRegistry.playS2C().register(RaidControllerAdminSnapshotPayload.TYPE, RaidControllerAdminSnapshotPayload.STREAM_CODEC);
    }
}
